### ISSUE TITLE
Version 3.3.4 causes massive console spam because "Calling client config when it is not yet available!"

### ISSUE THREAD

**Issue by SplendidAlakey** [Fuzss/puzzleslib-fabric#2]
**MC** 1.18.2
**Fabric API** 0.53.4
**PuzzlesLib** 3.3.4

After updating PuzzlesLib to 3.3.4, client logs get spammed with the same type of message referencing 3 of your mods: Easy Magic, Visual Workbench and Pickup Notifier. Reverting to PuzzlesLib 3.3.1 solves the issue.

Here are the relevant entries: https://gist.github.com/Footage2-Amply-Pounce/09eafb3692aba6dc436b3bbe6fbda8f6

I can't upload the entire log because it reached 1mil lines and gists can't handle it.

**Comment by Fuzss** [comment]
Do you also get the spam while playing or only during start-up?

**Comment by SplendidAlakey** [comment]
It seems to have started spamming in the main menu (hard to tell, because of the spam) and continued on during the gameplay. I only noticed because MMC dies when logs get too large. And I just realized that I could send the archived log: [removed]

Server logs were clean and didn't mention any problems at all.

**Comment by Fuzss** [comment]
Thanks, should be fixed now in v3.3.5.
